import LayoutProvider from "@/components/layout/layout.component";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import AppProvider from "./app-provider";
import AutoChangeToken from "@/components/auto-change-token.component";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const access_token = cookieStore.get("access_token")?.value;
    const refresh_token = cookieStore.get("access_token")?.value;
    return (
        <html lang="en">
            <body>
                <AppProvider access_token={access_token} refresh_token={refresh_token}>
                    <LayoutProvider>
                        {children}
                        <AutoChangeToken />
                    </LayoutProvider>
                </AppProvider>
                <ToastContainer />
            </body>
        </html>
    );
}
